Models/ErrorViewModel.cs
namespace MYSchool.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Students.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace MYSchool.Models
{
    public class Students
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string Fname { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string Lname { get; set; }

        [Required]
        [Display(Name = "Roll Number")]
        public  string RollNumber {get; set;}
        
        [Required]
        [Display(Name = "Class")]
        
        public string Class {get; set;}

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [MaxLength(10)]
        [Display(Name = "Phone")]
        public string Phone { get; set; }

        [Required]
        [MaxLength (100)]
        [Display(Name = "Address")]
        public string Address { get; set; }
    }



}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MYSchool.Models;
using System.Diagnostics;

namespace MYSchool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SchoolController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MYSchool.Models;
using MYSchool.Services.Interface;

namespace MYSchool.Controllers
{
    public class SchoolController : Controller
    {
        private readonly IStudentOperation _stu;

        public SchoolController(IStudentOperation stu)
        {
          _stu = stu;

            
        }
        // GET: SchoolController
        public ActionResult List()
        {

            var model = _stu.ALLStudents();
            if (model == null)
            {
                ViewBag.msg = "no" ;
            }
            return View(model);
        }

  
        // GET: SchoolController/Create
        public ActionResult Create()
        {
            var model = new Students();
            return View(model);
        }

        // POST: SchoolController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Students stu)
        {
            try
            {

                if(ModelState.IsValid)
                {
                  
                   var isSaved =  _stu.CreateNewStudentList(stu);

                    if (isSaved)
                    {
                        TempData["success"]= true;
                    }
                    else
                    {
                        TempData["success"] = false;
                    }

                    return RedirectToAction(nameof(Create));
                }
   
                return View(stu);
            }
            catch
            {
                return View();
            }
        }

        // GET: SchoolController/Edit/5
        public ActionResult Edit(int id)
        {
            
            var student = _stu.GetStudentById(id);
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,Students stu)
        {

            if (ModelState.IsValid)
            {
                var student = _stu.EditStudent(id, stu);
                if (student == null)
                {
                    TempData["success"] = false;

                }
                else
                {
                    TempData["success"] = true;
                }

                return RedirectToAction(nameof(List));

            }
            return RedirectToAction(nameof(Edit), new { id = id });

        }

  

        // GET: SchoolController/Delete/5
        public ActionResult Delete(int id)
        {
            var isDeleted  = _stu.DeleteStudent(id);

            return RedirectToAction(nameof(List));
        }

        // POST: SchoolController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


     
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/top-colleges-in-bangalore.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/BCB_Brazil_March_2023_447_5050.jpg" class="d-block w-100" alt="..." height="430px">
        </div>
        <div class="carousel-item">
            <img src="~/img/istockphoto-1351416161-612x612.jpg" class="d-block w-100" alt="..." height="430px">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

Views/School/Create.cshtml
@model Students
 @{
    ViewData["Title"] = "Home Page";
}


    <h1 class="display-6">New Admission Form 2024</h1>
    <hr />

<marquee class="text-danger">Admission has been opend and the last date for admission is 12-03-2024.</marquee>

@{
    @if (Convert.ToBoolean(TempData["Success"]))
    {
        <div class="alert alert-success">Student Added Successfully....</div>
    }

}


    <div class="row">

    <div class="col-sm-4">

        <img src="~/img/1266204.svg" width="100px" height="100px" />
    </div>
        <div class="col-sm-8">
        
            <form asp-action="Create" asp-controller="School" method="POST">


            @*//////*@
            <div class="row">

                <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="Fname" class="control-label"></label>
                        <input asp-for="Fname" class="form-control" />
                        <span asp-validation-for="Fname" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="Lname" class="control-label"></label>
                        <input asp-for="Lname" class="form-control" />
                        <span asp-validation-for="Lname" class="text-danger"></span>
                    </div>
                </div>


            </div>
            @*//////*@


            @*//////*@
            <div class="row">

                <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                </div>


            </div>
            @*//////*@
            @*//////*@
            <div class="row">

                <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="Class" class="control-label"></label>
                        <input asp-for="Class" class="form-control" />
                        <span asp-validation-for="Class" class="text-danger"></span>
                    </div>
                </div>


            </div>
            @*//////*@


            <div class="row">

             <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>

                  
             </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label asp-for="RollNumber" class="control-label"></label>
                        <input asp-for="RollNumber" class="form-control" />
                        <span asp-validation-for="RollNumber" class="text-danger"></span>
                    </div>
            </div>


            <input type="submit" value="Submit" class="btn btn-primary mt-4" />

            </form>

        </div>

       


 

    </div>

Views/School/Edit.cshtml
@model Students

<h1>Update Student Info :- @Model.Fname @Model.RollNumber</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fname" class="control-label"></label>
                <input asp-for="Fname" class="form-control" />
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lname" class="control-label"></label>
                <input asp-for="Lname" class="form-control" />
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RollNumber" class="control-label"></label>
                <input asp-for="RollNumber" class="form-control" />
                <span asp-validation-for="RollNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
      
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary mt-4" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List" class="mt-4">Back to List</a>
</div>

Views/School/List.cshtml
@model IEnumerable<Students> 
@{
    ViewData["Title"] = "Student List";
}

<h1 class="display-6">
   
  Students  🎓 

</h1>

@if (Convert.ToBoolean(TempData["success"]))
{

    <div class="alert alert-success">Student Info Updated Successfully....</div>
}


@{
    if(ViewBag.msg == "no")
    {
        <h1>No Students Found</h1>
    }
    else
    {
        <table class="table table-striped mt-4">
    

        <thead>
        <tr>
        <td>First Name</td>
                    <th>Last Name</th>
                    <th>Roll Number</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Class</th>
                    <th>Address</th>
                    <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        
        @{
            foreach (var item in Model)
                    {
                  <tr>

                        <td>@item.Fname</td>
                        <td>@item.Lname</td>
                        <td>@item.RollNumber</td>
                        <td>@item.Email</td>
                        <td>@item.Phone</td>
                        <td>@item.Class</td>
                        <td>@item.Address</td>

                            <td>

                                <a asp-action="Edit" asp-controller="School" class="text-info" asp-route-id="@item.Id"> ✏️ Edit</a>
                                <a asp-action="Delete" asp-controller="School" class="text-danger" asp-route-id="@item.Id"> 🗑️ Delete</a>
                        </td>
                        </tr>
                       
                    }
        }

        </tbody>

        </table>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MYSchool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MYSchool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sun🌞Shine Internation School</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="School" asp-action="Create">New Admission</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="School" asp-action="List">Students</a>
                        </li>     <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Queries</a>
                        </li>     <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SunShine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Students/Create.cshtml
@model MYSchool.Models.Students

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Students</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fname" class="control-label"></label>
                <input asp-for="Fname" class="form-control" />
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lname" class="control-label"></label>
                <input asp-for="Lname" class="form-control" />
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RollNumber" class="control-label"></label>
                <input asp-for="RollNumber" class="form-control" />
                <span asp-validation-for="RollNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Students/Delete.cshtml
@model MYSchool.Models.Students

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Students</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RollNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RollNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Students/Details.cshtml
@model MYSchool.Models.Students

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Students</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RollNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RollNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Students/Edit.cshtml
@model MYSchool.Models.Students

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Students</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fname" class="control-label"></label>
                <input asp-for="Fname" class="form-control" />
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lname" class="control-label"></label>
                <input asp-for="Lname" class="form-control" />
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RollNumber" class="control-label"></label>
                <input asp-for="RollNumber" class="form-control" />
                <span asp-validation-for="RollNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Students/Index.cshtml
@model IEnumerable<MYSchool.Models.Students>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RollNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Class)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RollNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>